services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
      target: express
    develop:
      watch:
        - action: sync
          path: ./apps/express
          target: ./prod/express
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/express/package.json
    env_file:
      - ./apps/express/.env
    restart: always
    environment:
      - OTEL_SERVICE_NAME=express
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_METRICS_EXPORTER_PORT=9464
    ports:
      - "3030:3030"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - express

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  grafana-storage:
