packages:
  - apps/*

catalog:
  "@opentelemetry/api": 1.9.0
  "@opentelemetry/auto-instrumentations-node": 0.60.0
  "@opentelemetry/core": 2.0.1
  "@opentelemetry/exporter-trace-otlp-grpc": 0.202.0
  "@opentelemetry/resources": 2.0.1
  "@opentelemetry/sdk-trace-base": 2.0.1
  "@opentelemetry/sdk-trace-node": 2.0.1
  "@opentelemetry/semantic-conventions": 1.34.0
  typescript: 5.8.3
  tsx: 4.19.4
  dotenv-cli: 8.0.0
  "@types/node": "22.15.30"
